/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LK2k1UeQVm8
 */
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { CardContent, Card, CardTitle, CardHeader, CardFooter } from "@/components/ui/card"

export function Cart() {
  return (
    (<div className="grid gap-4 lg:grid-cols-3 lg:gap-8 max-w-6xl mx-auto px-4">
      <div className="grid gap-2">
        <h1 className="font-bold text-3xl">Shopping Cart</h1>
        <p className="text-sm text-gray-500">You have 3 items in your cart</p>
      </div>
      <div className="col-span-2">
        <Card>
          <CardContent className="p-0">
            <div
              className="grid gap-4 sm:grid-cols-3 sm:gap-4 md:grid-cols-4 md:gap-6 lg:grid-cols-5 lg:gap-8 p-4">
              <div className="flex items-start gap-4 sm:col-span-2 md:col-span-1">
                <Checkbox className="mt-0.5" id="cart-item-1" />
                <img
                  alt="Thumbnail"
                  className="aspect-[3/4] object-cover border border-gray-200 rounded-lg overflow-hidden dark:border-gray-800"
                  height={200}
                  src="/placeholder.svg"
                  width={150} />
              </div>
              <div
                className="flex flex-col gap-1.5 sm:col-span-2 md:col-span-3 lg:col-span-4">
                <div className="grid gap-2">
                  <h2 className="font-semibold text-base sm:text-xl">The Midnight Library</h2>
                  <p className="text-sm text-gray-500">By Matt Haig</p>
                </div>
                <div className="hidden md:flex items-center gap-4">
                  <div className="flex items-center gap-0.5">
                    <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                    <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                    <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                    <StarIcon
                      className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
                    <StarIcon
                      className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
                  </div>
                </div>
                <div className="flex items-center gap-4 md:hidden">
                  <Button className="w-8 h-8" size="icon" variant="outline">
                    <ChevronUpIcon className="w-4 h-4" />
                    <span className="sr-only">Increase</span>
                  </Button>
                  <Input
                    className="form-input border-gray-300 w-12 sm:w-16 text-center"
                    max="10"
                    min="1"
                    type="number"
                    value="1" />
                  <Button className="w-8 h-8" size="icon" variant="outline">
                    <ChevronDownIcon className="w-4 h-4" />
                    <span className="sr-only">Decrease</span>
                  </Button>
                </div>
              </div>
              <div
                className="flex flex-col gap-1.5 justify-between sm:col-span-2 md:col-span-1 lg:col-span-1">
                <div className="flex items-center gap-4 md:hidden">
                  <div className="flex items-center gap-0.5">
                    <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                    <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                    <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                    <StarIcon
                      className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
                    <StarIcon
                      className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
                  </div>
                </div>
                <div className="font-semibold text-sm sm:text-base">€12.99</div>
                <Button size="sm">Save for later</Button>
              </div>
              <Button
                className="hidden md:flex justify-self-end sm:col-start-3 md:col-start-4 rounded-full border border-gray-200 p-2.5 dark:border-gray-800"
                size="icon"
                variant="outline">
                <TrashIcon className="w-4 h-4" />
                <span className="sr-only">Remove</span>
              </Button>
            </div>
            <div className="border-t" />
            <div className="grid gap-4 sm:grid-cols-2 p-4">
              <div className="flex items-center gap-4">
                <Button className="w-8 h-8" size="icon" variant="outline">
                  <ChevronUpIcon className="w-4 h-4" />
                  <span className="sr-only">Increase</span>
                </Button>
                <Input
                  className="form-input border-gray-300 w-12 sm:w-16 text-center"
                  max="10"
                  min="1"
                  type="number"
                  value="1" />
                <Button className="w-8 h-8" size="icon" variant="outline">
                  <ChevronDownIcon className="w-4 h-4" />
                  <span className="sr-only">Decrease</span>
                </Button>
              </div>
              <div className="flex items-center gap-4 sm:col-start-2">
                <Button className="w-8 h-8" size="icon" variant="outline">
                  <ChevronUpIcon className="w-4 h-4" />
                  <span className="sr-only">Increase</span>
                </Button>
                <Input
                  className="form-input border-gray-300 w-12 sm:w-16 text-center"
                  max="10"
                  min="1"
                  type="number"
                  value="1" />
                <Button className="w-8 h-8" size="icon" variant="outline">
                  <ChevronDownIcon className="w-4 h-4" />
                  <span className="sr-only">Decrease</span>
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="mt-4">
          <CardHeader>
            <CardTitle>Order Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2 text-sm">
              <div className="flex justify-between">
                <span>Subtotal</span>
                <span>€12.99</span>
              </div>
              <div className="flex justify-between">
                <span>Shipping</span>
                <span>€2.99</span>
              </div>
            </div>
            <div className="my-2" />
            <div className="flex justify-between font-semibold">
              <span>Total</span>
              <span>€15.98</span>
            </div>
          </CardContent>
          <CardFooter>
            <Button className="w-full" size="lg">
              Proceed to checkout
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function ChevronUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m18 15-6-6-6 6" />
    </svg>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
